version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      MICROBLOG_DB__uri: "postgresql://postgres:postgres@db:5432/${MICROBLOG_DB:-microblog}"
      MICROBLOG_DB__connect_args: "{}"
    volumes:
      - .:/home/app/api
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    build: postgres
    image: microblog_postgres-13-alpine-multi-user
    volumes:
      - $HOME/.postgres/microblog_db/data/postgresql:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_DBS=microblog, microblog_test
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres